"""Bake title-screen assets into Python source.

Two outputs:

* ``aw/title_logo.py`` — packed 2bpp mask of the Another World logo
  (transparent / white interior / black outline), rendered from the
  SVG at the target on-screen size.
* ``aw/title_backdrop.py`` — packed 4bpp framebuffer + 16-colour
  palette for the title screen backdrop, quantised down from one of
  the 20th Anniversary Edition's high-res scene BMPs.

Reserved palette slots (consistent across both modules):

* 3 = black (logo outline)
* 7 = white (logo interior)
* 9 = UI hint text (cool blue-grey)
* 10 = UI selection highlight (warm yellow)

The remaining 12 slots are filled by the backdrop quantiser.

Run once when the source assets change:

    uv run --with cairosvg --with pillow python tools/build_title_logo.py
"""

import io
import os
import sys
import textwrap

import cairosvg
from PIL import Image, ImageFilter

_HERE = os.path.dirname(os.path.abspath(__file__))

LOGO_W = 268
LOGO_H = 92
SUPER = 4  # super-sample to keep edges crisp before threshold
SVG_PATH = os.path.join(_HERE, "..", "game", "title_logo.svg")
LOGO_OUT_PATH = os.path.join(_HERE, "..", "aw", "title_logo.py")

BACKDROP_W = 320
BACKDROP_H = 200
BACKDROP_SRC = os.path.join(
    _HERE, "..", "game", "BMP", "data1728x1080", "e3052.bmp",
)
BACKDROP_OUT_PATH = os.path.join(_HERE, "..", "aw", "title_backdrop.py")

# Palette slot reservations — these match aw/title.py's expectations.
_RESERVED_SLOTS = {3, 7, 9, 10, 11}
_RESERVED_COLORS = {
    3: (0x00, 0x00, 0x00),    # logo outline / dark UI
    7: (0xFF, 0xFF, 0xFF),    # logo interior / primary text
    9: (0xA0, 0xB8, 0xD8),    # hint text
    10: (0xFF, 0xE0, 0x50),   # selection highlight
    11: (0xFF, 0x60, 0x40),   # error red
}

# Classification codes packed into the mask.
T = 0  # transparent — keep backdrop pixel
W = 1  # white interior
K = 2  # black outline


def render_filled_mask(svg_path, w, h):
    """Render the SVG and return a binary 'is letter' mask.

    Both the black fills and the gold trim count as 'letter' — we'll
    grow that by one pixel for the outline and keep the original as
    the white interior.
    """
    png = cairosvg.svg2png(
        url=svg_path, output_width=w * SUPER, output_height=h * SUPER,
    )
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    img = img.resize((w, h), Image.LANCZOS)
    mask = Image.new("L", (w, h), 0)
    src = img.load()
    dst = mask.load()
    for y in range(h):
        for x in range(w):
            r, g, b, a = src[x, y]
            if a < 96:
                continue
            # Any non-transparent SVG pixel — black fill, gold trim,
            # or anti-aliased blend — counts as 'letter'.
            dst[x, y] = 255
    return mask


def build_mask_layers(filled):
    """Return (interior_mask, outline_mask) as PIL 'L' images.

    Outline = dilate(filled, 1px) - filled
    Interior = filled (original)
    """
    w, h = filled.size
    dilated = filled.filter(ImageFilter.MaxFilter(3))
    outline = Image.new("L", (w, h), 0)
    f = filled.load()
    d = dilated.load()
    o = outline.load()
    for y in range(h):
        for x in range(w):
            if d[x, y] >= 128 and f[x, y] < 128:
                o[x, y] = 255
    return filled, outline


def pack_2bpp(interior, outline, w, h):
    """Pack into 2 bits per pixel: 4 pixels per byte, MSB first."""
    iv = interior.load()
    ov = outline.load()
    n = (w * h + 3) // 4
    out = bytearray(n)
    for y in range(h):
        for x in range(w):
            if iv[x, y] >= 128:
                code = W
            elif ov[x, y] >= 128:
                code = K
            else:
                code = T
            i = y * w + x
            byte_i = i >> 2
            shift = (3 - (i & 3)) * 2
            out[byte_i] |= code << shift
    return bytes(out)


def write_module(out_path, data, w, h):
    """Write the constants to a Python module."""
    # Format the bytes as escaped string literals, 24 bytes per line
    lines = []
    chunk = 24
    for i in range(0, len(data), chunk):
        lines.append("    " + repr(bytes(data[i:i + chunk])))
    body = "\n".join(lines)

    src = textwrap.dedent('''\
        """Generated by tools/build_title_logo.py — do not edit by hand.

        Packed 2bpp mask of the Another World logo for the title screen.
        Codes per pixel: 0=transparent, 1=white interior, 2=black outline.
        """

        LOGO_W = {w}
        LOGO_H = {h}

        # Adjacent bytes literals concatenate at parse time, so this is a
        # single bytes object — no runtime join required.
        LOGO_DATA = (
        {body}
        )
        ''').format(w=w, h=h, body=body)

    with open(out_path, "w") as f:
        f.write(src)


def quantize_backdrop(src_path, w, h):
    """Quantise the backdrop to 12 colours that fit alongside the
    reserved UI/logo slots.

    Returns (palette, packed_4bpp_bytes) where palette is a list of
    16 (r, g, b) tuples and the packed data has each pixel mapped to
    its final palette slot.
    """
    img = Image.open(src_path).convert("RGB").resize((w, h), Image.LANCZOS)
    free_slots = sorted(set(range(16)) - _RESERVED_SLOTS)
    n_free = len(free_slots)  # 12

    # Median-cut to N colours, then upgrade indices to final slots.
    quant = img.quantize(colors=n_free, method=Image.MEDIANCUT, dither=Image.NONE)
    raw_pal = quant.getpalette()
    quant_palette = [(raw_pal[3 * i], raw_pal[3 * i + 1], raw_pal[3 * i + 2])
                     for i in range(n_free)]

    palette = [(0, 0, 0)] * 16
    for slot, rgb in _RESERVED_COLORS.items():
        palette[slot] = rgb
    for i, slot in enumerate(free_slots):
        palette[slot] = quant_palette[i]

    # Build a remap from quantised index → final slot
    remap = {i: slot for i, slot in enumerate(free_slots)}

    # Pack as 4bpp (2 pixels per byte, MSB = left pixel)
    px = quant.load()
    stride = w // 2
    packed = bytearray(stride * h)
    for y in range(h):
        for x in range(w):
            slot = remap[px[x, y]]
            off = y * stride + (x >> 1)
            if x & 1:
                packed[off] = (packed[off] & 0xF0) | (slot & 0x0F)
            else:
                packed[off] = (packed[off] & 0x0F) | ((slot & 0x0F) << 4)
    return palette, bytes(packed)


def write_backdrop_module(out_path, palette, data, w, h):
    """Write aw/title_backdrop.py with palette + packed data."""
    pal_lines = []
    for i, (r, g, b) in enumerate(palette):
        pal_lines.append("    (0x{:02X}, 0x{:02X}, 0x{:02X}),  # {:2d}"
                         .format(r, g, b, i))
    pal_block = "\n".join(pal_lines)

    chunk = 24
    data_lines = []
    for i in range(0, len(data), chunk):
        data_lines.append("    " + repr(bytes(data[i:i + chunk])))
    data_block = "\n".join(data_lines)

    src = textwrap.dedent('''\
        """Generated by tools/build_title_logo.py — do not edit by hand.

        Packed 4bpp backdrop framebuffer + 16-entry RGB palette for the
        title screen. Slots 3, 7, 9, 10 are reserved for UI; the rest
        are filled by the quantised source bitmap.
        """

        BACKDROP_W = {w}
        BACKDROP_H = {h}

        BACKDROP_PALETTE = (
        {pal}
        )

        # Adjacent bytes literals concatenate at parse time.
        BACKDROP_DATA = (
        {data}
        )
        ''').format(w=w, h=h, pal=pal_block, data=data_block)

    with open(out_path, "w") as f:
        f.write(src)


def main():
    if not os.path.exists(SVG_PATH):
        print("Missing SVG at {}".format(SVG_PATH), file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(BACKDROP_SRC):
        print("Missing backdrop BMP at {}".format(BACKDROP_SRC), file=sys.stderr)
        sys.exit(1)

    # --- Logo ---
    print("Rendering logo SVG → {}x{} mask".format(LOGO_W, LOGO_H))
    filled = render_filled_mask(SVG_PATH, LOGO_W, LOGO_H)
    interior, outline = build_mask_layers(filled)
    logo_data = pack_2bpp(interior, outline, LOGO_W, LOGO_H)
    print("  packed {} bytes ({} px)".format(len(logo_data), LOGO_W * LOGO_H))
    write_module(LOGO_OUT_PATH, logo_data, LOGO_W, LOGO_H)
    print("  wrote {}".format(LOGO_OUT_PATH))

    # --- Backdrop ---
    print("Quantising backdrop {} → {}x{}".format(
        os.path.basename(BACKDROP_SRC), BACKDROP_W, BACKDROP_H))
    palette, backdrop_data = quantize_backdrop(BACKDROP_SRC, BACKDROP_W, BACKDROP_H)
    print("  packed {} bytes (16-colour palette)".format(len(backdrop_data)))
    write_backdrop_module(BACKDROP_OUT_PATH, palette, backdrop_data,
                          BACKDROP_W, BACKDROP_H)
    print("  wrote {}".format(BACKDROP_OUT_PATH))

    # --- Combined preview ---
    preview = Image.new("RGB", (BACKDROP_W, BACKDROP_H))
    bp = preview.load()
    stride = BACKDROP_W // 2
    for y in range(BACKDROP_H):
        for x in range(BACKDROP_W):
            byte = backdrop_data[y * stride + (x >> 1)]
            slot = (byte >> 4) if not (x & 1) else (byte & 0x0F)
            bp[x, y] = palette[slot]
    iv = interior.load()
    ov = outline.load()
    logo_x = (BACKDROP_W - LOGO_W) // 2
    logo_y = 12
    for y in range(LOGO_H):
        for x in range(LOGO_W):
            if iv[x, y] >= 128:
                bp[logo_x + x, logo_y + y] = (255, 255, 255)
            elif ov[x, y] >= 128:
                bp[logo_x + x, logo_y + y] = (0, 0, 0)
    preview.resize((BACKDROP_W * 2, BACKDROP_H * 2), Image.NEAREST) \
        .save("/tmp/title_preview.png")
    print("Combined preview at /tmp/title_preview.png")


if __name__ == "__main__":
    main()
